### ISSUE TITLE
Installing on mac high sierra

### ISSUE THREAD

**Issue by bharris12** [naikai/sake#69]
This is more of a comment, and would be nice to change in the README

Even after you use brew to install gcc, it is not the default C compiler on mac. brew names it gcc-7. So if you want r to use that compiler when installing dependencies you need to add CC=gcc-7 as an argument :

 `devtools::install_github("naikai/sake", CC=gcc-7)`

**Comment by status-five** [comment]
Updated in [Updates README to add a comment on installation on MAC OSX ](https://github.com/naikai/sake/commit/ab95930ecfbe8048aed37f7d8a67ab7210b62dba)
