### ISSUE TITLE
Errors in installing sake pacakge

### ISSUE THREAD

**Issue by kysbbubbu** [naikai/sake#70]
Hello

I have difficulty in installing sake pacakge

The below is the console of my R studio.

How can I do to fix the error?

Thanks for your help...

<console>
Downloading GitHub repo naikai/sake@master
from URL https://api.github.com/repos/naikai/sake/zipball/master
Installing sake
Downloading GitHub repo renozao/NMF@master
from URL https://api.github.com/repos/renozao/NMF/zipball/master
Installing NMF
--2018-04-26 12:37:02--  https://cran.rstudio.com/src/contrib/dendextend_1.7.0.tar.gz
Resolving cran.rstudio.com (cran.rstudio.com)... 52.84.188.72
Connecting to cran.rstudio.com (cran.rstudio.com)|52.84.188.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1747651 (1.7M) [application/x-gzip]
Saving to: ‘/tmp/RtmpYmGag2/dendextend_1.7.0.tar.gz’

     0K .......... .......... .......... .......... ..........  2% 7.94M 0s
    50K .......... .......... .......... .......... ..........  5% 11.9M 0s
   100K .......... .......... .......... .......... ..........  8% 11.6M 0s
   150K .......... .......... .......... .......... .......... 11% 11.5M 0s
   200K .......... .......... .......... .......... .......... 14% 11.5M 0s
   250K .......... .......... .......... .......... .......... 17% 11.6M 0s
   300K .......... .......... .......... .......... .......... 20% 11.6M 0s
   350K .......... .......... .......... .......... .......... 23% 8.86M 0s
   400K .......... .......... .......... .......... .......... 26% 11.7M 0s
   450K .......... .......... .......... .......... .......... 29% 11.6M 0s
   500K .......... .......... .......... .......... .......... 32% 11.8M 0s
   550K .......... .......... .......... .......... .......... 35% 11.6M 0s
   600K .......... .......... .......... .......... .......... 38% 11.7M 0s
   650K .......... .......... .......... .......... .......... 41% 11.7M 0s
   700K .......... .......... .......... .......... .......... 43% 11.8M 0s
   750K .......... .......... .......... .......... .......... 46% 8.85M 0s
   800K .......... .......... .......... .......... .......... 49% 11.6M 0s
   850K .......... .......... .......... .......... .......... 52% 11.7M 0s
   900K .......... .......... .......... .......... .......... 55% 11.7M 0s
   950K .......... .......... .......... .......... .......... 58% 11.5M 0s
  1000K .......... .......... .......... .......... .......... 61% 11.7M 0s
  1050K .......... .......... .......... .......... .......... 64% 11.6M 0s
  1100K .......... .......... .......... .......... .......... 67% 11.6M 0s
  1150K .......... .......... .......... .......... .......... 70% 8.88M 0s
  1200K .......... .......... .......... .......... .......... 73% 11.6M 0s
  1250K .......... .......... .......... .......... .......... 76% 11.7M 0s
  1300K .......... .......... .......... .......... .......... 79% 11.7M 0s
  1350K .......... .......... .......... .......... .......... 82% 11.6M 0s
  1400K .......... .......... .......... .......... .......... 84% 11.7M 0s
  1450K .......... .......... .......... .......... .......... 87% 11.6M 0s
  1500K .......... .......... .......... .......... .......... 90% 11.7M 0s
  1550K .......... .......... .......... .......... .......... 93% 8.63M 0s
  1600K .......... .......... .......... .......... .......... 96% 11.6M 0s
  1650K .......... .......... .......... .......... .......... 99% 13.2M 0s
  1700K ......                                                100%  349M=0.1s

2018-04-26 12:37:02 (11.2 MB/s) - ‘/tmp/RtmpYmGag2/dendextend_1.7.0.tar.gz’ saved [1747651/1747651]

Installing dendextend
--2018-04-26 12:37:04--  https://cran.rstudio.com/src/contrib/fpc_2.1-11.tar.gz
Resolving cran.rstudio.com (cran.rstudio.com)... 52.84.188.72
Connecting to cran.rstudio.com (cran.rstudio.com)|52.84.188.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 152399 (149K) [application/x-gzip]
Saving to: ‘/tmp/RtmpYmGag2/fpc_2.1-11.tar.gz’

     0K .......... .......... .......... .......... .......... 33% 5.20M 0s
    50K .......... .......... .......... .......... .......... 67% 11.6M 0s
   100K .......... .......... .......... .......... ........  100% 14.9M=0.02s

2018-04-26 12:37:04 (8.66 MB/s) - ‘/tmp/RtmpYmGag2/fpc_2.1-11.tar.gz’ saved [152399/152399]

Installing fpc
--2018-04-26 12:37:05--  https://cran.rstudio.com/src/contrib/flexmix_2.3-14.tar.gz
Resolving cran.rstudio.com (cran.rstudio.com)... 52.84.188.72
Connecting to cran.rstudio.com (cran.rstudio.com)|52.84.188.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1169493 (1.1M) [application/x-gzip]
Saving to: ‘/tmp/RtmpYmGag2/flexmix_2.3-14.tar.gz’

     0K .......... .......... .......... .......... ..........  4% 8.02M 0s
    50K .......... .......... .......... .......... ..........  8% 11.6M 0s
   100K .......... .......... .......... .......... .......... 13% 11.7M 0s
   150K .......... .......... .......... .......... .......... 17% 11.6M 0s
   200K .......... .......... .......... .......... .......... 21% 11.7M 0s
   250K .......... .......... .......... .......... .......... 26% 11.6M 0s
   300K .......... .......... .......... .......... .......... 30% 11.7M 0s
   350K .......... .......... .......... .......... .......... 35% 8.89M 0s
   400K .......... .......... .......... .......... .......... 39% 11.7M 0s
   450K .......... .......... .......... .......... .......... 43% 11.7M 0s
   500K .......... .......... .......... .......... .......... 48% 11.7M 0s
   550K .......... .......... .......... .......... .......... 52% 11.6M 0s
   600K .......... .......... .......... .......... .......... 56% 11.7M 0s
   650K .......... .......... .......... .......... .......... 61% 11.5M 0s
   700K .......... .......... .......... .......... .......... 65% 10.3M 0s
   750K .......... .......... .......... .......... .......... 70% 11.2M 0s
   800K .......... .......... .......... .......... .......... 74% 11.8M 0s
   850K .......... .......... .......... .......... .......... 78% 9.45M 0s
   900K .......... .......... .......... .......... .......... 83% 14.6M 0s
   950K .......... .......... .......... .......... .......... 87% 9.07M 0s
  1000K .......... .......... .......... .......... .......... 91% 11.6M 0s
  1050K .......... .......... .......... .......... .......... 96% 11.6M 0s
  1100K .......... .......... .......... .......... ..        100% 15.2M=0.1s

2018-04-26 12:37:06 (11.1 MB/s) - ‘/tmp/RtmpYmGag2/flexmix_2.3-14.tar.gz’ saved [1169493/1169493]

Installing flexmix
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools4376222579c0/flexmix' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘flexmix’ ...
** package ‘flexmix’ successfully unpacked and MD5 sums checked
** R
** data
** inst
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called ‘lme4’
Error : unable to load R code in package ‘flexmix’
ERROR: lazy loading failed for package ‘flexmix’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/flexmix’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools4376360db227/fpc' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

ERROR: dependency ‘flexmix’ is not available for package ‘fpc’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/fpc’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools43767b2a2854/dendextend' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

ERROR: dependency ‘fpc’ is not available for package ‘dendextend’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/dendextend’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools43765e48c1a8/renozao-NMF-e46bec1' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

ERROR: dependency ‘dendextend’ is not available for package ‘NMF’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/NMF’
Installation failed: Command failed (1)
Downloading GitHub repo rstudio/d3heatmap@colorlabels
from URL https://api.github.com/repos/rstudio/d3heatmap/zipball/colorlabels
Installing d3heatmap
--2018-04-26 12:37:10--  https://cran.rstudio.com/src/contrib/dendextend_1.7.0.tar.gz
Resolving cran.rstudio.com (cran.rstudio.com)... 52.84.188.72
Connecting to cran.rstudio.com (cran.rstudio.com)|52.84.188.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1747651 (1.7M) [application/x-gzip]
Saving to: ‘/tmp/RtmpYmGag2/dendextend_1.7.0.tar.gz’

     0K .......... .......... .......... .......... ..........  2% 7.65M 0s
    50K .......... .......... .......... .......... ..........  5% 11.7M 0s
   100K .......... .......... .......... .......... ..........  8% 11.7M 0s
   150K .......... .......... .......... .......... .......... 11% 11.6M 0s
   200K .......... .......... .......... .......... .......... 14% 11.7M 0s
   250K .......... .......... .......... .......... .......... 17% 9.13M 0s
   300K .......... .......... .......... .......... .......... 20% 8.82M 0s
   350K .......... .......... .......... .......... .......... 23% 8.18M 0s
   400K .......... .......... .......... .......... .......... 26% 11.6M 0s
   450K .......... .......... .......... .......... .......... 29% 11.7M 0s
   500K .......... .......... .......... .......... .......... 32% 11.7M 0s
   550K .......... .......... .......... .......... .......... 35% 11.4M 0s
   600K .......... .......... .......... .......... .......... 38% 8.23M 0s
   650K .......... .......... .......... .......... .......... 41% 9.27M 0s
   700K .......... .......... .......... .......... .......... 43% 11.4M 0s
   750K .......... .......... .......... .......... .......... 46% 9.11M 0s
   800K .......... .......... .......... .......... .......... 49% 11.7M 0s
   850K .......... .......... .......... .......... .......... 52% 11.6M 0s
   900K .......... .......... .......... .......... .......... 55% 11.7M 0s
   950K .......... .......... .......... .......... .......... 58% 11.6M 0s
  1000K .......... .......... .......... .......... .......... 61% 11.4M 0s
  1050K .......... .......... .......... .......... .......... 64% 11.7M 0s
  1100K .......... .......... .......... .......... .......... 67% 11.6M 0s
  1150K .......... .......... .......... .......... .......... 70% 8.86M 0s
  1200K .......... .......... .......... .......... .......... 73% 11.7M 0s
  1250K .......... .......... .......... .......... .......... 76% 11.7M 0s
  1300K .......... .......... .......... .......... .......... 79% 11.6M 0s
  1350K .......... .......... .......... .......... .......... 82% 11.6M 0s
  1400K .......... .......... .......... .......... .......... 84% 11.7M 0s
  1450K .......... .......... .......... .......... .......... 87% 11.6M 0s
  1500K .......... .......... .......... .......... .......... 90% 7.99M 0s
  1550K .......... .......... .......... .......... .......... 93% 7.36M 0s
  1600K .......... .......... .......... .......... .......... 96% 8.03M 0s
  1650K .......... .......... .......... .......... .......... 99% 8.53M 0s
  1700K ......                                                100%  390M=0.2s

2018-04-26 12:37:10 (10.3 MB/s) - ‘/tmp/RtmpYmGag2/dendextend_1.7.0.tar.gz’ saved [1747651/1747651]

Skipping dendextend, it is already being installed.
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools437634e4343f/rstudio-d3heatmap-5685d6a' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

ERROR: dependency ‘dendextend’ is not available for package ‘d3heatmap’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/d3heatmap’
Installation failed: Command failed (1)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpYmGag2/devtools43767151571a/naikai-sake-ab95930' --library='/home/kys/R/x86_64-pc-linux-gnu-library/3.2'  \
  --install-tests 

ERROR: dependencies ‘NMF’, ‘d3heatmap’ are not available for package ‘sake’
* removing ‘/home/kys/R/x86_64-pc-linux-gnu-library/3.2/sake’
Installation failed: Command failed (1)

**Comment by status-five** [comment]
For clarification, what operating system are you running? 

This output shows that you are failing to locate the `lme4` package. The first thing I would try is to try to install this package: `install.packages("lme4")`

**Comment by kysbbubbu** [comment]
I already installed the ubuntu dependencies... 

But fortunately I fixed the problem 

I suspect the OS problem, and I tried to install ubuntu 18 ver via virtualbox machine on win 10 system.

And then ... it worked!! 
thanks for your kind help
