### ISSUE TITLE
errors in stalling sake

### ISSUE THREAD

**Issue by helianthuszhu** [naikai/sake#71]
Hi, I am trying to install sake on mac (ver 10.13.4) but failed at the beginning. Here is the details.
> devtools::install_github("naikai/sake") #
Downloading GitHub repo naikai/sake@master
Error: HTTP error 404.
  Not Found
  Rate limit remaining: 45/60
  Rate limit reset at: 2018-11-09 09:11:45 UTC
> devtools::install_github("naikai/sake", CC=gcc-7)
Downloading GitHub repo naikai/sake@master
Error: HTTP error 404.
  Not Found
  Rate limit remaining: 9/60
  Rate limit reset at: 2018-11-09 09:11:45 UTC.
Can anyone tell me what the problem is? Thanks.

**Comment by status-five** [comment]
It looks like your computer can't find github or the repo (and thus the 404), you might want to try
`curl https://github.com/naikai/sake`
on the unix command line to see if it's something about your computer. 

Another workaround may be to use _githubinstall_ 
```
install.packages("githubinstall")
library("githubinstall")
githubinstall("sake")
```

**Comment by helianthuszhu** [comment]
Thank you so much. I tried to install sake using packrat and it worked this time.
