### ISSUE TITLE
set jquery version in global.R

### ISSUE THREAD

**Issue by psterk** [naikai/sake#77]
Hi,

conditionalPanel code was not behaving on one of my installations, but worked on another one. It turned out that the shiny.jquery version was 3.x on one of my machines, which throws exceptions with sake code. You could force shiny to use an older version, e.g. by adding the following option in global.R:

`options(shiny.jquery.version = 1)`

**Comment by naikai** [comment]
Hope this solves the problem: https://github.com/naikai/sake/commit/1f13232a31e5d99874e765fd358ee96061be6ae0
